language: python
python:
  - "2.7"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install tornado 
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - pip install .
# command to run tests
script: 
  - nosetests --with-coverage --cover-package=pyrpc
after_success:
  - coveralls

